"""Add UserAdmin model

Revision ID: 45b5376e3f5f
Revises: 5a7794cd974c
Create Date: 2024-04-13 21:58:53.539655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b5376e3f5f'
down_revision = '5a7794cd974c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_queries', schema=None) as batch_op:
        batch_op.drop_column('result')

    # ### end Alembic commands ###
