"""Change context logic

Revision ID: 23cd79afb9de
Revises: 0d4cf15f0637
Create Date: 2024-03-26 15:34:52.668062

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '23cd79afb9de'
down_revision = '0d4cf15f0637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint('sessions_user_id_key', type_='unique')
        batch_op.drop_constraint('sessions_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('sessions_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_unique_constraint('sessions_user_id_key', ['user_id'])

    # ### end Alembic commands ###
