"""Add first_payment to User

Revision ID: 07cbf4e099f7
Revises: db9dc532365b
Create Date: 2024-03-21 13:31:05.456622

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '07cbf4e099f7'
down_revision = 'db9dc532365b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_payment', sa.Boolean(), nullable=True))

    op.execute("UPDATE users SET first_payment = true")
    op.alter_column("users", "first_payment", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('first_payment')

    # ### end Alembic commands ###
