"""Edit ImageQuery

Revision ID: 45cc5b5d4293
Revises: 0dd37370eea9
Create Date: 2024-03-28 16:14:44.877734

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '45cc5b5d4293'
down_revision = '0dd37370eea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_queries', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
