"""Initial migration.4

Revision ID: 5a7794cd974c
Revises: 4f1718df3d21
Create Date: 2024-04-13 13:37:36.656665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a7794cd974c'
down_revision = '4f1718df3d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_admin', schema=None) as batch_op:
        batch_op.alter_column('hash_password',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_admin', schema=None) as batch_op:
        batch_op.alter_column('hash_password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
