"""Change context logic

Revision ID: 5d2a9b57bca1
Revises: bf5417f2d3f6
Create Date: 2024-03-26 17:47:06.928771

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5d2a9b57bca1'
down_revision = 'bf5417f2d3f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint('sessions_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('sessions_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
