"""Add Role model

Revision ID: adca8bde0c62
Revises: 07cbf4e099f7
Create Date: 2024-03-21 17:14:54.353522

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'adca8bde0c62'
down_revision = '07cbf4e099f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_generation_roles',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('txt_model_role_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, 'text_generation_roles', ['txt_model_role_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('txt_model_role_id')

    op.drop_table('text_generation_roles')
    # ### end Alembic commands ###
