"""Change context logic

Revision ID: 0d4cf15f0637
Revises: a43c99bd3c53
Create Date: 2024-03-26 15:13:44.452614

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0d4cf15f0637'
down_revision = 'a43c99bd3c53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.drop_column('is_active')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_session_id', sa.BigInteger(), nullable=True))
        batch_op.create_unique_constraint(None, ['text_session_id'])
        batch_op.create_foreign_key(None, 'sessions', ['text_session_id'], ['id'])
        batch_op.drop_column('context')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('text_session_id')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
