"""Change tts_mode type

Revision ID: 0faa6cbf25e9
Revises: 45b5376e3f5f
Create Date: 2024-04-17 13:21:28.620616

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0faa6cbf25e9'
down_revision = '45b5376e3f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('tts_mode',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('tts_mode',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
