"""Edit FK

Revision ID: c59d042964be
Revises: 868bfc2f1e39
Create Date: 2024-03-21 12:03:58.964117

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c59d042964be'
down_revision = '868bfc2f1e39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.drop_constraint('invoices_mother_invoice_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'invoices', ['mother_invoice_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tariffs', schema=None) as batch_op:
        batch_op.drop_constraint('tariffs_main_tariff_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tariffs', ['main_tariff_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_tariff_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tariffs', ['tariff_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('users_tariff_id_fkey', 'tariffs', ['tariff_id'], ['id'])

    with op.batch_alter_table('tariffs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tariffs_main_tariff_id_fkey', 'tariffs', ['main_tariff_id'], ['id'])

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('invoices_mother_invoice_id_fkey', 'invoices', ['mother_invoice_id'], ['id'])
        batch_op.alter_column('user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
