"""Edit Strings

Revision ID: db9dc532365b
Revises: e6b5fad7458b
Create Date: 2024-03-21 12:38:21.816214

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'db9dc532365b'
down_revision = 'e6b5fad7458b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('mother_invoice_id',
                              existing_type=sa.BIGINT(),
                              type_=sa.Integer(),
                              nullable=True)
        batch_op.drop_constraint('invoices_mother_invoice_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_foreign_key('invoices_mother_invoice_id_fkey', 'invoices', ['mother_invoice_id'], ['id'],
                                    ondelete='SET NULL')
        batch_op.alter_column('mother_invoice_id',
                              existing_type=sa.Integer(),
                              type_=sa.BIGINT(),
                              nullable=False)

    # ### end Alembic commands ###
