"""Add mother_invoice to user

Revision ID: c725cfd58bea
Revises: 677f39a47846
Create Date: 2024-04-18 11:26:49.564116

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c725cfd58bea'
down_revision = '677f39a47846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mother_invoice_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mother_invoice_id')

    # ### end Alembic commands ###
