"""Edit Strings

Revision ID: e6b5fad7458b
Revises: c46f4963e867
Create Date: 2024-03-21 12:36:37.287243

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e6b5fad7458b'
down_revision = 'c46f4963e867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tariffs', schema=None) as batch_op:
        batch_op.alter_column('main_tariff_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_constraint('tariffs_main_tariff_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tariffs', schema=None) as batch_op:
        batch_op.create_foreign_key('tariffs_main_tariff_id_fkey', 'tariffs', ['main_tariff_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('main_tariff_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)

    # ### end Alembic commands ###
