"""SET NULL on queries

Revision ID: e6560f0d6a3e
Revises: 9ab586100ddf
Create Date: 2024-05-15 13:22:54.173985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6560f0d6a3e'
down_revision = '9ab586100ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_queries', schema=None) as batch_op:
        batch_op.drop_constraint('image_queries_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('service_queries', schema=None) as batch_op:
        batch_op.drop_constraint('service_queries_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('text_queries', schema=None) as batch_op:
        batch_op.drop_constraint('text_queries_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_text_session_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'sessions', ['text_session_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('video_queries', schema=None) as batch_op:
        batch_op.drop_constraint('video_queries_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_queries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('video_queries_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('users_text_session_id_fkey', 'sessions', ['text_session_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('text_queries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('text_queries_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('service_queries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('service_queries_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('image_queries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('image_queries_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
