"""Sum field in invoice

Revision ID: 677f39a47846
Revises: f26104353953
Create Date: 2024-04-17 19:51:41.567561

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '677f39a47846'
down_revision = 'f26104353953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sum', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('sum')

    # ### end Alembic commands ###
