"""links m2m2 on delete

Revision ID: b9d20b762637
Revises: d1873f26eb7f
Create Date: 2024-05-13 18:45:11.667751

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b9d20b762637'
down_revision = 'd1873f26eb7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_referral_link_association', schema=None) as batch_op:
        batch_op.drop_constraint('user_referral_link_association_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_referral_link_association_referal_link_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'referal_links', ['referal_link_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_referral_link_association', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_referral_link_association_referal_link_id_fkey', 'referal_links', ['referal_link_id'], ['id'])
        batch_op.create_foreign_key('user_referral_link_association_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
