"""Edit Strings

Revision ID: c46f4963e867
Revises: c59d042964be
Create Date: 2024-03-21 12:33:24.684357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c46f4963e867'
down_revision = 'c59d042964be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tariffs', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['main_tariff_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tariffs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
