"""Add fields to ImageQuery

Revision ID: 0dd37370eea9
Revises: db486e7da275
Create Date: 2024-03-27 16:36:25.543815

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0dd37370eea9'
down_revision = 'db486e7da275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('index', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_queries', schema=None) as batch_op:
        batch_op.drop_column('index')
        batch_op.drop_column('action')

    # ### end Alembic commands ###
