"""Change context logic

Revision ID: 0a2d8e62e4a5
Revises: 23cd79afb9de
Create Date: 2024-03-26 15:46:24.376969

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0a2d8e62e4a5'
down_revision = '23cd79afb9de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_text_session_id_key', type_='unique')
        batch_op.drop_constraint('users_text_session_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'sessions', ['text_session_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('users_text_session_id_fkey', 'sessions', ['text_session_id'], ['id'])
        batch_op.create_unique_constraint('users_text_session_id_key', ['text_session_id'])

    # ### end Alembic commands ###
