"""Edit User

Revision ID: 868bfc2f1e39
Revises: 3e0e04c6f7ca
Create Date: 2024-03-20 15:51:50.001533

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '868bfc2f1e39'
down_revision = '3e0e04c6f7ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referal_links',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('buys_cnt', sa.Integer(), nullable=False),
    sa.Column('buys_sum', sa.Integer(), nullable=False),
    sa.Column('new_users', sa.Integer(), nullable=False),
    sa.Column('bot_link', sa.String(), nullable=False),
    sa.Column('site_link', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_link'),
    sa.UniqueConstraint('site_link')
    )
    with op.batch_alter_table('tariffs', schema=None) as batch_op:
        batch_op.alter_column('main_tariff_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('chatgpt_daily_limit', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('dalle_2_daily_limit', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('sd_daily_limit', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('token_balance', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('tts_mode', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('payment_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('payment_tries', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('recurring', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('referal_link_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, 'referal_links', ['referal_link_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('referal_link_id')
        batch_op.drop_column('recurring')
        batch_op.drop_column('payment_tries')
        batch_op.drop_column('payment_time')
        batch_op.drop_column('tts_mode')
        batch_op.drop_column('token_balance')
        batch_op.drop_column('sd_daily_limit')
        batch_op.drop_column('dalle_2_daily_limit')
        batch_op.drop_column('chatgpt_daily_limit')
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('tariffs', schema=None) as batch_op:
        batch_op.alter_column('main_tariff_id',
               existing_type=sa.BIGINT(),
               nullable=False)

    op.drop_table('referal_links')
    # ### end Alembic commands ###
