"""Edit Role model

Revision ID: 77e1e5f1856c
Revises: adca8bde0c62
Create Date: 2024-03-21 18:55:40.354338

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '77e1e5f1856c'
down_revision = 'adca8bde0c62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_generation_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_generation_roles', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
